name: Pylint

on:
  push:
    branches: [ "main" ]
    paths:
    - 'django/**'
    - 'BuildTools/**'
    - '.github/workflows/pylint.yml'
  pull_request:
    branches: [ "main" ]
    paths:
    - 'django/**'
    - 'BuildTools/**'
    - '.github/workflows/pylint.yml'
    types: [opened, ready_for_review, synchronize, reopened]

jobs:
  pylint_test:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - name: checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Check if Django files changed
      id: file-check
      run: |
        git fetch origin main > /dev/null 2>&1
        changed=$(git diff --name-only origin/main...HEAD | grep '^django/' || true)
        if [[ -z "$changed" ]]
        then
          echo "No Django changes."
          echo "skip=true" >> $GITHUB_OUTPUT
        else
          echo "skip=false" >> $GITHUB_OUTPUT
        fi
    - name: Set up Python ${{ matrix.python-version }}
      if: steps.file-check.outputs.skip == 'false'
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      if: steps.file-check.outputs.skip == 'false'
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint
        python -m pip install -r requirements.txt
    - name: Analysing the code with pylint
      if: steps.file-check.outputs.skip == 'false'
      run: |
        pylint --disable C0103,C0200,C0201,C0206,C0303,C0411,C0413,C0415,E1121,R0912,R0915,W0511,W0702,W0718,W0719,R0801,R0901,R0901,R0902,R0913,R0914,R0904,R0903,R0917,R1716,E1101,W0107,W0223,W1203 $(git ls-files '*.py' | grep -vP 'django/.*/(migrations|tests)')
