# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: React Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: Build FrontEnd
      run: |
        docker compose -f BuildTools/docker-compose.yml up -d --build --remove-orphans frontend
    - name: Test with Jest
      run: |
        docker exec stocks_frontend /bin/bash -c 'cd src; npm test'
